[settings]
name = BIX

[display]
accounting = false
logs = false
trace = false
single = false
parse = false
json = true

[fields]
hide=
show=
show_example_all = CTransaction:all|CReceipt:all|CLogEntry:all|CTrace:all|CTraceResult:all|CTraceAction:all|CParameter:all
show_example_logs = \
	CTransaction: none| \
	CReceipt: none, logs \
	CLogEntry: none, articulatedLog \
	CTrace: none
	
[formats]
trans_fmt = [{BLOCKNUMBER}]\t[{TRANSACTIONINDEX}]\t[{HASH}]
txrans_fmt = [{TIMESTAMP}]\t[{BLOCKNUMBER}]\t[{TRANSACTIONINDEX}]\t[{TRACEID}]\t[{FROM}]\t[{TO}]\t[{ETHER}]\t[{GAS}]\t[{GASPRICE}]\t[{GASUSED}]\t[TRUE{b:ISERROR}]\t[{ENCODING}]\t[{ARTICULATED}]

[[watches]]
list = [
    { address = "0xb3104b4b9da82025e8b9f8fb28b3553ce2f67069", name = "BIX",   firstBlock = 4319840, lastBlock = 6500000 },
]
