openapi: 3.0.0
info:
  title: TrueBlocks API
  description: An API for accessing cached Ethereum blockchain data and accounts
  contact:
    email: jrush@quickblocks.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.8.04
servers:
- url: http://localhost:8080
  description: Local endpoints
- url: https://virtserver.swaggerhub.com/trueblocks/TrueBlocks/0.8.04
  description: SwaggerHub API Auto Mocking
tags:
[{TAGS}]paths:
[{PATHS}]components:
  schemas:
    response:
      required:
      - result
      type: object
      properties:
        data:
          type: object
          example:
          - $ref: '#/components/schemas/scrape_response'
          - $ref: '#/components/schemas/trans_response'
        error:
          type: array
          example:
          - error 1
          - error 2
          items:
            type: string
    scrape_response:
      type: string
      example: Scrape response
    trans_response:
      type: string
      example: Trans response
