[settings]
name = "NAME"

[display]
accounting = false
debug = false
logs = false
trace = false
single = false
autocorrect = false
parse = false

[fields]
#hide = "CTransaction:traces"
show = "CLogEntry:topics,CLogEntry:data"

[formats]
trans_fmt = "[{BLOCKNUMBER}]\t[{TRANSACTIONINDEX}]\t[{HASH}]"
#trans_fmt = " \"[{DATE}]\",\"[{FROM}]\",\"[{TO}]\",\"[{ETHER}]\""

[[watches]]
list = [
    { address = "ADDR", name = "NAME", firstBlock = FIRST }
]
