[settings]
name=accts
index = 33587264

[display]
accounting = true
debug = true
logs = true
trace = true
single = true
autocorrect = true
parse = false

[formats]
trans_fmt = [{DATE} ] \
            [{BLOCKNUMBER} ][{TRANSACTIONINDEX} ] \
            [{FROM} ][{TO} ][{ETHER} ][{ISERROR} ] \
            [\r\n\tarticulated:\t{ARTICULATED}] \
            [\r\n\tgas cost:\t{GASCOST}][ (used/price: {GASUSED}][ @ {GASPRICE})]
#trace_fmt = { [{DATESH}], [{TIME}], [{FROM}], [{TO}], [{VALUE}], [{GASCOST}], [{INPUT}] }

[[watches]]
list = [
    { address = "0xa92e6abc1156b6ed4948cc962cb60f250d422c68", name = "Main Wallet",        firstBlock = 1971529, color = "white_b"   },
    { address = "0x00a3819199113fc6a6e6ba1298afde7377e2009b", name = "Laptop Wallet",      firstBlock = 2867899, color = "magenta_b" },
    { address = "0xb97073b754660bb356dfe12f78ae366d77dbc80f", name = "Tip Jar",            firstBlock = 1986055, color = "blue_b"    },
    { address = "0xfd6c5ac853391486d25ddd5cefb1f7040ee31c2c", name = "Token Holder",       firstBlock = 2420364, color = "green_b"   },
    { address = "0xf1aa581f353005ba3765b81bf52d6b1c488c2767", name = "One Ether",          firstBlock = 1986062, color = "red_b"     },
    { address = "0xd31f381ad54386895852f311fc3be2008c88cb27", name = "Play Wallet",        firstBlock = 2597778, color = "yellow_b"  },
    { address = "0x654e7f49b474e2f5ac29cc5f2f0d41c8a93d6d0a", name = "MetaMask Wallet",    firstBlock = 2972204, color = "teal_b"    },
    { address = "0x85979379cb90d63fe944763b42b9ec4b49573ea7", name = "Nates Wallet",       firstBlock = 2593109, color = "white_c"   },
    { address = "0x7E02ee81df2b100C3292636e0813d71192D8b071", name = "Bitrex Wallet",      firstBlock = 4342440, color = "green_c"   },
    { address = "0x00ad1a7b0ef4d3c5070d73b9412b6ed22efb7533", name = "Hacker Camp Wallet", firstBlock = 3189894, color = "magenta_c", lastBlock = 2873699 },
    { address = "0x31f54a9d0c9817bb9e6ca1d17ca20d8ea718bc66", name = "Old MEW Wallet",     firstBlock = 3900000, color = "blue_c",    lastBlock = 3900000 },
    { address = "0x00a6ef05a497236a1ea611857f52884593f63f8c", name = "Play Account 2",     firstBlock = 3900000, color = "green_c",   lastBlock = 3900000 },
    { address = "0x9519afbc60719a83c470ceec41e32d3e4b8b262e", name = "GH_DAO_Wallet",      firstBlock = 1383378, color = "red_c",     lastBlock = 1975800 },
    { address = "0xfd23407a31f54413e32043adb7b1ee61a6e04027", name = "OLD_WALLET",         firstBlock = 1235820, color = "blue_b",    lastBlock = 1434025 },
    { address = "0xcb1547417575261c4d84cab3e989acfd9f9ee35c", name = "GH_2_Wallet",        firstBlock = 1438181, color = "yellow_c",  lastBlock = 1975779 },
    { address = "0x3464e758c8372d7cb536eaf9f5a126d3f574f4c3", name = "EtherSlurp",         firstBlock = 1559924, color = "teal_c",    lastBlock = 2603045 },
    { address = "0xe583ac239693c716ee5567c7da61c96647d691e5", name = "Account_4",          firstBlock = 1589769, color = "white_b",   lastBlock = 1973555 },
    { address = "0x77d0967ffddbad3aba301837208392573da29299", name = "NatesOldWallet",     firstBlock = 1477483, color = "magenta_b", lastBlock = 1974407 },
    { address = "0x10ed2372778da1b9d96782c894b752d8a647deb8", name = "NatesOldWallet2",    firstBlock = 1724673, color = "blue_b",    lastBlock = 1848186 },
    { address = "0x713b73c3994442b533e6a083ec968e40606810ec", name = "EEAR",               firstBlock = 1387025, color = "red_c",     lastBlock = 1470405 },
    { address = "0x2b61CD90B5591604B3D969Ca9eb944D59be6f5A7", name = "Old_EEAR",           firstBlock = 1385714, color = "magenta_b", lastBlock = 1386546 },
    { address = "0xc430503c9f7cade47eb28958e734ee6255fe143b", name = "GiftOfFriendship",   firstBlock = 2694532, color = "yellow_c",  lastBlock = 2694564 },
    { address = "0x3e575510b9304ff417c2e4d420d1314dc3f13687", name = "Friend_Ar",          firstBlock = 1488777, color = "blue_b",    lastBlock = 1987505 },
    { address = "0x6d343663e55f734781e278b2b41a36c99e0bac40", name = "Friend_A",           firstBlock = 2610051, color = "blue_b",    lastBlock = 2677451 },
    { address = "0x9e5adb4e5c299654c2f0619624f7c9eb7b9a3a1a", name = "Friend_D",           firstBlock = 2511426, color = "blue_b",    lastBlock = 2511433 },
    { address = "0xf6f1cd99578ea87b67ae2bf7e9ca3e7e99d0fb98", name = "Exch_K1",            firstBlock = 1973555, color = "green_c",   lastBlock = 1973640 },
    { address = "0xbb43f212b7b47bab7164ce74a07bd1d61aef1ee8", name = "Exch_K2",            firstBlock = 1925718, color = "green_c",   lastBlock = 1956807 },
    { address = "0xf6b0b85aa3a40e9d3e821847a65bd37d56ac78c2", name = "Exch_K3",            firstBlock = 1447148, color = "green_c",   lastBlock = 1915285 },
    { address = "0xb3a0f8e3c7e44949011b18cf5a92ebae41923419", name = "Exch_K4",            firstBlock = 1973788, color = "green_c",   lastBlock = 3359914 },
    { address = "0x10821bc0260fe58606d2fd97fda2113d4ab4a1ca", name = "Exch_K5",            firstBlock = 1974267, color = "green_c",   lastBlock = 1974270 },
    { address = "0xa7e1819bb646e0b8c0dd6b5dba91212536e98cc5", name = "Exch_K6",            firstBlock = 1342525, color = "green_c",   lastBlock = 1973842 },
    { address = "0x268e6834d5b40745849157cae0e5715190135f10", name = "Exch_K7",            firstBlock = 1974407, color = "green_c",   lastBlock = 1974418 },
    { address = "0xc0fab372fad6613c3be2bb1378b2857a86c5ad90", name = "Exch_K8",            firstBlock = 1975779, color = "green_c",   lastBlock = 1975804 },
    { address = "0x2eb0056C62ddDd0D5bD29FD51fe795B3Cb0B9be1", name = "QuickNodes node",    firstBlock = 4162912, color = "blue_b"    },
    { address = "0x62428f78fe0118447b9668ae867b4bf6a40c2d9c", name = "Augur Web Wallet",   firstBlock = 4402980, color = "white_b"   },
    { address = "0x48a74e18b38b153c54dd4f7c0c9f9f112a83a4ee", name = "Ledger",             firstBlock = 4915357, color = "blue_b"    },
    { address = "0xdd449471bdc5a4d98f1a7d05e35b4cb55ebed441", name = "Nate Ledger",        firstBlock = 4916351, color = "blue_b"    },
    { address = "0x3b161D57F482cd2dFBB626f0307ef92b3B094Fce", name = "NewMetaMask",        firstBlock = 4834045, color = "white_b"   },
]
named = [
    { address = "0x314159265dd8dbb310642f98f50c066173c1259b", name = "ENS (Main)"          },
    { address = "0x6090a6e47849629b7245dfa1ca21d94cd15878ef", name = "ENS Registrar"       },
    { address = "0x012233b3c8177f0778d910ed88170b82de3bfe57", name = "Defunct ENS Regist"  },
    { address = "0xbb9bc244d798123fde783fcc1c72d3bb8c189413", name = "The DAO"             },
    { address = "0xbf4ed7b27f1d666546e30d74d50d173d20bca754", name = "DAO_Withdrawl"       },
    { address = "0xc7e165ebdad9eeb8e5f5d94eef3e96ea9739fdb2", name = "Dao.consider.it"     },
    { address = "0xaa1a6e3e6ef20068f7f8d8c835d2d22fd5116444", name = "ReplaySafeSplit"     },
    { address = "0x2910543af39aba0cd09dbb2d50200b3e800a63d2", name = "Kraken_Exch_1"       },
    { address = "0x53d284357ec70ce289d6d64134dfac8e511c8a3d", name = "Kraken_Exch_2"       },
    { address = "0xfa52274dd61e1643d2205169732f29114bc240b3", name = "Kraken_Exch_3"       },
    { address = "0x5f742383b6d1298980030d6af943b76cdd902143", name = "Etherplay"           },
    { address = "0x9ae98746eb8a0aeee5ff2b6b15875313a986f103", name = "Parity SMS Verifier" },
    { address = "0x7cb57b5a97eabe94205c07890be4c1ad31e486a8", name = "Tip_MyEtherWallet"   },
    { address = "0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359", name = "Tip_Ethereum"        },
    { address = "0x7ed1e469fcb3ee19c0366d829e291451be638e59", name = "Philly Meetup"       },
    { address = "0x7cb57b5a97eabe94205c07890be4c1ad31e486a8", name = "Friend_TVO"          },
    { address = "0x8f53781799515e5dc8f5d00c528940cae99ac969", name = "Friend_CP"           },
    { address = "0x5adf43dd006c6c36506e2b2dfa352e60002d22dc", name = "GiveEth"             }
]
