[settings]
name = Gnosis
index = 24704

[display]
accounting = false
debug = false
logs = false
trace = false
single = false
autocorrect = true
parse = false

[formats]
trans_fmt = [{DATE} ] \
            [{BLOCKNUMBER} ][{TRANSACTIONINDEX} ] \
            [{FROM} ][{TO} ][{ETHER} ][{ISERROR} ] \
            [\r\n\tarticulated:\t{ARTICULATED}] \
            [\r\n\tgas cost:\t{GASCOST}][ (used/price: {GASUSED}][ @ {GASPRICE})]

[[watches]]
list = [
	{ address = "0xbe4e25443df23382228e6347b06565edd838f901", name = "DutchAuctionOwner", firstBlock = 3445080, color = "magenta_b" },
	{ address = "0x851b7f3ab81bd8df354f0d7640efcd7288553419", name = "AuctionWallet",     firstBlock = 3557579, color = "white_b"   },
	{ address = "0x1d0dcc8d8bcafa8e8502beaeef6cbd49d3affcdc", name = "DutchAuction",      firstBlock = 3557583, color = "blue_b"    },
	{ address = "0x6810e776880C02933D47DB1b9fc05908e5386b96", name = "TokenContract",     firstBlock = 3557596, color = "green_b"   },
	{ address = "0x19076bd01e86fa3d76334e27d4b8e6789688a42d", name = "Related",           firstBlock = 3567875, color = "teal_b"    }
]
