[settings]
name = "[{NAME}]"

[display]
accounting = false
debug = false
logs = false
trace = false
single = false
parse = false

[formats]
trans_fmt = "[{TIMESTAMP}]\t[{BLOCKNUMBER}]\t[{TRANSACTIONINDEX}]\t[{FROM}]\t[{TO}]\t[{VALUE}]\t[{GAS}]\t[{GASPRICE}]\t[{GASUSED}]\t[{ISERROR}]\t[{ENCODING}]\t[{FUNCTION}]"

[[watches]]
[{JSON_WATCH}]

# make sure to always put arrays at the end of the file
