[display]
accounting = false
debug = false
logs = false
trace = false
bloom = false
single = false
parse = false

[formats]
screen_fmt = \
    { "date": "[{DATE}]", "position": "[{BLOCKNUMBER}].[{TRANSACTIONINDEX}]", \
    "from": "[{FROM}]", "to": "[{TO}]", "ether": "[{ETHER}]", "gasCost": "[{GASCOST}]", \
    "hash": "[{HASH}]" }
verbose_fmt = [{HEAD}]\n\
	\tdate: @[{DATE}]# timestamp: @[{TIMESTAMP}]# ether: @[{ETHER}]#\n\
	\tfrom: @[{FROM}]# to: @[{TO}]# value: @[{w:30:VALUE}]# \n\
	\thash: @[{HASH}]# \n\
	\tblockNumber: @[{BLOCKNUMBER}]# txIndex: @[{TRANSACTIONINDEX}]#\n\
	\tinput: @[{INPUT}]#\n\
	[{P}]

[[watches]]
[{JSON_WATCH}]
