[settings]
name = fyn
index = 270848

[display]
accounting = true
debug = true
logs = true
trace = true
single = true
autocorrect = true
parse = false

[formats]
trans_fmt = [{DATE} ] \
            [{BLOCKNUMBER} ][{TRANSACTIONINDEX} ] \
            [{FROM} ][{TO} ][{ETHER} ][{ISERROR} ] \
            [\r\n\tarticulated:\t{ARTICULATED}] \
            [\r\n\tgas cost:\t{GASCOST}][ (used/price: {GASUSED}][ @ {GASPRICE})]

[[watches]]
list = [
    { address = "0x88FCFBc22C6d3dBaa25aF478C578978339BDe77a", name = "Token", firstBlock = 3854480, color = "green_c" }
,    { address = "0xb1021477444c6566509e1b80d2c99e9603a31c47", name = "Second", firstBlock = 3854480, color = "teal_c" }
]

# make sure to always put arrays at the end of the file
