[settings]
name = beltran

[display]
accounting = false
debug = false
logs = false
trace = true
single = false
parse = false

[formats]
trans_fmt = [{TIMESTAMP}]\t[{BLOCKNUMBER}]\t[{TRANSACTIONINDEX}]\t[{TRACEID}]\t[{FROM}]\t[{TO}]\t[{ETHER}]\t[{GAS}]\t[{GASPRICE}]\t[{GASUSED}]\t[TRUE{b:ISERROR}]\t[{ENCODING}]\t[{ARTICULATED}]

[[watches]]
list = [
    { address = "0xf8faffbd5a3e3b5abf567521d1811b96036a300f", name = "Nth Round", firstBlock = 6100000, color = "green_c" }
]
