[settings]
name = Tierion
index = 4353

[display]
accounting = false
debug = false
logs = false
trace = false
single = false
autocorrect = true
parse = false

[formats]
trans_fmt = [{DATE} ] \
            [{BLOCKNUMBER} ][{TRANSACTIONINDEX} ] \
            [{FROM} ][{TO} ][{ETHER} ][{ISERROR} ] \
            [\r\n\tarticulated:\t{ARTICULATED}] \
            [\r\n\tgas cost:\t{GASCOST}][ (used/price: {GASUSED}][ @ {GASPRICE})]

[[watches]]
list = [
    { address = "0x08f5a9235b08173b7569f83645d2c7fb55e8ccd8", name = "TierionNetworkToken", firstBlock = 4201265, color = "green_c" },
    { address = "0x3CD5Cc3Aa9fFDb7Fb08520F55F9955022AB27cfC", name = "TierionRelated1",     firstBlock = 4203023, color = "white_b" }
]
