[version]
current=0.2.0

[settings]
cachePath=/Users/jrush/.quickBlocks/slurps/
api_provider=EtherScan
api_url=http://etherscan.io/apis
api_key=<NOT_SET>
block_data_path=<NOT_SET>

[display]
fmt_fieldList=
fmt_txt_file=[{HEADER}]\n[{RECORDS}]
fmt_txt_record=[{FIELDS}]\n
fmt_txt_field=\t[{FIELD}]
fmt_csv_file=[{HEADER}]\n[{RECORDS}]
fmt_csv_record=[{FIELDS}]\n
fmt_csv_field=["{FIELD}"],
fmt_html_file=<table>\n[{HEADER}]\n[{RECORDS}]</table>\n
fmt_html_record=\t<tr>\n[{FIELDS}]</tr>\n
fmt_html_field=\t\t<td>[{FIELD}]</td>\n
fmt_json_file=[{RECORDS}]\n
fmt_json_record=\n        {\n[{FIELDS}]        },
fmt_json_field="[{p:FIELD}]":"[{FIELD}]",
fmt_custom_file=file:custom.txt
fmt_custom_record=fmt_txt_record
fmt_custom_field=fmt_txt_field
