[settings]
name = etherTip
index = 8916992

[display]
accounting = true
debug = true
logs = true
trace = true
single = true

[fields]
hide=
show=

[formats]
txrans_fmt = [{BLOCKNUMBER}]\t[{TRANSACTIONINDEX}]\t[{HASH}]
trans_fmt = [{DATE} ] \
            [{BLOCKNUMBER} ][{TRANSACTIONINDEX} ] \
            [{FROM} ][{TO} ][{ETHER} ][{ISERROR} ] \
            [\r\n\tarticulated:\t{ARTICULATED}] \
            [\r\n\tgas cost:\t{GASCOST}][ (used/price: {GASUSED}][ @ {GASPRICE})]

[[watches]]
list = [
    { address = "0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359", name = "FoundationTipJar", firstBlock = 988725, color = "magenta_b", enabled = true },
    { address = "0x89205a3a3b2a69de6dbf7f01ed13b2108b2c43e7", name = "Unicorns",         firstBlock = 988949, color = "blue_b", enabled = true }
]
