[settings]
name = DAO

[display]
accounting = false
debug = false
logs = false
trace = false
single = false
autocorrect = false
parse = false

[fields]
hide=CTransaction:traces

[formats]
trans_fmt = [{BLOCKNUMBER}]\t[{TRANSACTIONINDEX}]\t[{HASH}]
#trans_fmt = "[{DATE}]","[{FROM}]","[{TO}]","[{ETHER}]"

[[watches]]
list = [
    { address = "0xbb9bc244d798123fde783fcc1c72d3bb8c189413", name = "DAO", firstBlock = 0 }
]
