name: GitHub Actions Demo
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Prerequistes
        run: |
          sudo apt install build-essential git cmake python python-dev libcurl3-dev clang-format jq
      - name: Setup SSH Key
        run: |
          mkdir ~/.ssh
          echo $SSH_PRIVATE_KEY > ~/.ssh/github_action
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/github_action
          ls -la ~/.ssh
        env:
          SSH_PRIVATE_KEY : ${{secrets.SSH_PRIVATE_KEY}}
      - name: Run SSH Process and Tests
        run: |
          ${{secrets.SSH_COMMAND}}
          ls -la ~/.ssh
      - name: Build TrueBlocks
        run: |
          echo "Ah1"
      - name: Run SSH Process and Tests
        run: |
          ${{secrets.SSH_COMMAND}} &
      
      - run: echo "🍏 This job's status is ${{ job.status }}."
