name: GitHub Actions Demo
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Prerequistes
        run: |
          sudo apt install build-essential git cmake python python-dev libcurl3-dev clang-format jq
      - name: Setup SSH Key
        run: |
          mkdir ~/.ssh
          echo $SSH_PRIVATE_KEY > ~/.ssh/github_action
          chmod -R og-rwx ~/.ssh
        env:
          SSH_PRIVATE_KEY : ${{secrets.SSH_PRIVATE_KEY}}
      - name: Build TrueBlocks
        run: |
          mkdir build && cd build
          cmake ../src
          make -j 4
      - name: Run SSH Process
        run: |
          ${{secrets.SSH_COMMAND}} &
          make test-all
      
      - run: echo "🍏 This job's status is ${{ job.status }}."
